services:
  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend-app
    ports:
      - "3000:3000"

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/backend-app
    ports:
      - "8080:8080"
    command: "--spring.profiles.active=prod"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=/grafana

volumes:
  grafana-storage:
