spring:
  application:
    name: app
  profiles:
    active: local
  config:
    import: application-secret.yml
  jackson:
    time-zone: Asia/Seoul


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
      prometheus:
        enabled: true
