spring:
  application:
    name: app
  profiles:
    active: local
  config:
    import: application-secret.yml
  jackson:
    time-zone: Asia/Seoul


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
      prometheus:
        enabled: true


resilience4j:
  circuitbreaker:
    instances:
      openai:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      naverNews:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      jobList:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      jobDetail:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s